### PR TITLE
Update deploy instructions

### PR DESCRIPTION
**Pull request by alishaevn**
# Summary
add instructions on how to deploy to the yale infrastructure

### CODE REVIEW

**Review by maxkadel — CHANGES_REQUESTED** [review]
This refers to the blacklight version several times, rather than management. 

I'm wondering if this would more appropriately live in the Camerata repo, since it has more to do with all the projects, and only include things that are specific to the management app here?

**Comment by alishaevn** [comment]
> This refers to the blacklight version several times, rather than management.
> 
> I'm wondering if this would more appropriately live in the Camerata repo, since it has more to do with all the projects, and only include things that are specific to the management app here?

whoops! thought I had caught those. 


mmm. I guess that's a discussion to be had. my preference though is having the instructions in the repo I'm working with instead of needing to bounce between two.

**Comment by alishaevn** [comment]
removed the references to blacklight

**Comment by maxkadel** [comment]
> > This refers to the blacklight version several times, rather than management.
> > I'm wondering if this would more appropriately live in the Camerata repo, since it has more to do with all the projects, and only include things that are specific to the management app here?
> 
> whoops! thought I had caught those.
> 
> mmm. I guess that's a discussion to be had. my preference though is having the instructions in the repo I'm working with instead of needing to bounce between two.

That makes sense - my concern is that documentation goes stale so quickly, and if we try to maintain the same information on each repo, it's going to get out of sync really quickly. I'd rather have documentation that will be the same for every repo in the project be maintained in a single central place, so that it only has to be maintained there.

**Comment by alishaevn** [comment]
> That makes sense - my concern is that documentation goes stale so quickly, and if we try to maintain the same information on each repo, it's going to get out of sync really quickly. I'd rather have documentation that will be the same for every repo in the project be maintained in a single central place, so that it only has to be maintained there.

@maxkadel  valid point if there were all the same. 
releasing cam doesn't appear to be the same as blacklight/management though. it doesn't have anything about the github token in its readme and the yale infrastructure release doesn't apply either. so I think it would wind up being a bunch of "if / else if / else" statements in the camerata repo that could also lead the user back to the repo they're actually deploying for if it's something specific to that repo.

**Review by maxkadel — APPROVED** [review]

**Pull request merged**
